### ISSUE TITLE
build on OS X el capitan

### ISSUE THREAD

**Issue by ghost** [tobspr/LUI#4]
Hi,

As I try to compile, the following error creeps almost at the beginning. I'm using OSX El Capitan.

Version: 1.10.0
Using Python 2.7
Traceback (most recent call last):
  File "makepanda/makepanda.py", line 448, in <module>
    SdkLocateMSPlatform(STRMSPLATFORMVERSION)
NameError: name 'SdkLocateMSPlatform' is not defined

**Comment by tobspr** [comment]
Hey,

the makepanda file in the repo is a bit outdated, thats probably because it
fails. I will try to make an updated version today :)

**Comment by tobspr** [comment]
Should be solved, LUI is using my module builder now

**Comment by ghost** [comment]
Hi,

Thank you! But not really, I'm on a Mac :smiley: 

File "/Users/blabla/Downloads/LUI-master/Scripts/common.py", line 73, in get_panda_lib_path
    raise NotImplementedError("Unsupported OS")
NotImplementedError: Unsupported OS

**Comment by tobspr** [comment]
Oh well, sorry, I must have missed that! It is a bit ufortunate that I don't have a mac for testing this, but I will work on adding support for building on mac on my module builder

**Comment by rdb** [comment]
This may have been fixed by tobspr/P3DModuleBuilder#8.
