### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by tongjianjun** [tobspr/LUI#51]
I tried it in the win10+vs2010+cmake environment, and the installation failed. Could you please provide a lui.pyd file to me?

**Comment by rdb** [comment]
What kind of error message did you get?  Which precise version of Panda3D are you using?

**Comment by tongjianjun** [comment]
Panda3D == 1.9.4

the error message as below:
--------------------------------------------------------------------------------
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(207): error C2061: syntax error : identifier 'size' [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(207): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(208): error C2061: syntax error : identifier 'width' [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(208): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(208): error C2535: 'int LUIBaseElement::MAKE_PROPERTY2(void)' : member function already defined or declared [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(209): error C2061: syntax error : identifier 'height' [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(209): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(209): error C2535: 'int LUIBaseElement::MAKE_PROPERTY2(void)' : member function already defined or declared [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(214): error C2061: syntax error : identifier 'parent' [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(214): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(214): error C2535: 'int LUIBaseElement::MAKE_PROPERTY2(void)' : member function already defined or declared [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(207): error C2061: syntax error : identifier 'size' [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(207): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(208): error C2061: syntax error : identifier 'width' [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(208): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(208): error C2535: 'int LUIBaseElement::MAKE_PROPERTY2(void)' : member function already defined or declared [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(209): error C2061: syntax error : identifier 'height' [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(209): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(209): error C2535: 'int LUIBaseElement::MAKE_PROPERTY2(void)' : member function already defined or declared [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(214): error C2061: syntax error : identifier 'parent' [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(214): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]
         d:\soft\panda3d\lui-master\source\luiBaseElement.h(214): error C2535: 'int LUIBaseElement::MAKE_PROPERTY2(void)' : member function already defined or declared [D:\soft\panda3d\LUI-master\win_amd64_panda1.9.4_py27_vc100\lui.vcxproj]

    64 Warning(s)
    177 Error(s)

Time Elapsed 00:02:20.88
Traceback (most recent call last):
  File "build.py", line 52, in <module>
    run_cmake_build(config, args)
  File "D:\soft\panda3d\LUI-master\scripts\setup.py", line 174, in run_cmake_build
    try_execute("cmake", "--build", ".", "--config", configuration, "--", core_option)
  File "D:\soft\panda3d\LUI-master\scripts\common.py", line 253, in try_execute
    raise Exception("Process had non-zero returncode:", process.returncode)
Exception: ('Process had non-zero returncode:', 1)
