### ISSUE TITLE
building works but there is an import error?

### ISSUE THREAD

**Issue by BMaxV** [tobspr/LUI#61]
Hi, tried your project, didn't work this is the problem I ran into:
```
Traceback (most recent call last):
  File "B_BlockText.py", line 3, in <module>
    from DemoFramework import DemoFramework
  File "/home/max/Documents/Python/LUI/Demos/DemoFramework.py", line 15, in <module>
    from LUIRegion import LUIRegion
  File "/home/max/Documents/Python/LUI/Demos/../Builtin/LUIRegion.py", line 7, in <module>
    from panda3d.lui import LUIRegion as __LUIRegion
NameError: name 'TypeHandle' is not defined

```

**Comment by rdb** [comment]
Try importing `panda3d.core` first.

**Comment by BMaxV** [comment]
No that doesn't work either.

To clarify, it's the demos in the project that aren't working.

**Comment by NeueraEntmt** [comment]
Same issue :( Builded successfully and copied lui.pyd to 'C:\Panda3D-1.11.0-x64\panda3d' but giving an import error;
```
    >> python 01_MinimalExample.py
from panda3d.lui import LUIObject as _LUIObject
ImportError: DLL load failed while importing lui: Belirtilen modül bulunamadı. (Can't find module!)
```
